spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: wu010602
mybatis:
  mapper-locations: classpath*:com/example/geniusmarket/mapper/*.xml
  type-aliases-package: com.example.geniusmarket.pojo
#server:
#  port: 9500
#  ssl:
#    key-store: classpath:ssl.pfx
#    key-store-password: 0RTSUL2f
#    key-store-type: PKCS12