spring:
  datasource:
    url: jdbc:mysql://121.41.25.13:7894/geniusMrket?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: geniusMrket
    password: geniusMrket12345
mybatis:
  mapper-locations: classpath*:com/example/geniusmarket/mapper/*.xml
  type-aliases-package: com.example.geniusmarket.pojo
server:
   port: 9543
   http: 9500
   ssl:
      key-store: ssl.pfx
      key-store-password: 0RTSUL2f
      key-store-type: PKCS12